package com.edi.backend.messaging;

/**
 * Message published to the {@code document.processing} queue.
 *
 * <p>The worker consumes this message to trigger AI processing.
 * {@code correlationId} is a UUID generated by the backend on upload and threaded through
 * the entire async chain (queue → worker → ai-service → result queue → backend consumer)
 * so every log line across all services can be correlated.
 *
 * <p>Production note: this would be replaced by an Avro or Protobuf schema registered in a
 * Schema Registry, giving backward/forward compatibility guarantees across service versions.
 */
public record DocumentProcessingMessage(
        String correlationId,
        String documentId,
        String fileUrl,
        String userId) {}
